[package]
name = "example-print"
version = "4.10.34"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.pretty-version]
path = "../pretty-version"
